# Generated by Django 2.0.7 on 2018-07-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_xəbərlər_shekil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xəbərlər',
            name='id',
        ),
        migrations.AlterField(
            model_name='xəbərlər',
            name='başliq',
            field=models.CharField(max_length=2000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='xəbərlər',
            name='shekil',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='foto/'),
        ),
    ]
