# Generated by Django 2.0.7 on 2018-07-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_auto_20180726_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xəbərlər',
            name='mezmun',
            field=models.TextField(),
        ),
    ]
