# Generated by Django 2.0.7 on 2018-07-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0004_auto_20180727_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='xəbərlər',
            name='muellif',
            field=models.CharField(default='Naməlum', max_length=2000),
        ),
        migrations.AlterField(
            model_name='xəbərlər',
            name='tarix',
            field=models.DateTimeField(verbose_name='Tarix'),
        ),
    ]
