# Generated by Django 2.0.7 on 2018-07-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0005_auto_20180727_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xəbərlər',
            name='muellif',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
