# Generated by Django 2.0.7 on 2018-07-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0006_auto_20180727_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layihə',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200)),
                ('idareEden', models.CharField(max_length=200)),
                ('elaqeNomresi', models.CharField(max_length=200)),
                ('bashlamaTarix', models.DateTimeField(verbose_name='Başlayır')),
                ('bitmeTarix', models.DateTimeField(verbose_name='Bitir')),
                ('shekil', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='foto/')),
                ('meqsed', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tərəfdaş',
            fields=[
                ('ad', models.CharField(max_length=200)),
                ('soyad', models.CharField(max_length=200)),
                ('nomre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('shekil', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='foto/')),
            ],
        ),
    ]
