# Generated by Django 2.0.7 on 2018-07-27 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0007_layihə_tərəfdaş'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layihə',
            options={'verbose_name_plural': 'Layihələr'},
        ),
        migrations.AlterModelOptions(
            name='tərəfdaş',
            options={'verbose_name_plural': 'Tərəfdaşlar'},
        ),
        migrations.AlterModelOptions(
            name='xəbərlər',
            options={'verbose_name_plural': 'Xəbərlər'},
        ),
    ]
