# Generated by Django 2.0.7 on 2018-07-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0008_auto_20180727_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layihə',
            name='shekil',
            field=models.ImageField(default='pic_folder/None/proj.png', upload_to='foto/'),
        ),
        migrations.AlterField(
            model_name='tərəfdaş',
            name='shekil',
            field=models.ImageField(default='pic_folder/None/user.png', upload_to='foto/'),
        ),
        migrations.AlterField(
            model_name='xəbərlər',
            name='shekil',
            field=models.ImageField(default='pic_folder/None/news.jpg', upload_to='foto/'),
        ),
    ]
