# Generated by Django 2.0.7 on 2018-07-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0009_auto_20180727_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layihə',
            name='shekil',
            field=models.ImageField(default='layihe/proj.png', upload_to='layihe/'),
        ),
        migrations.AlterField(
            model_name='tərəfdaş',
            name='shekil',
            field=models.ImageField(default='terefdas/user.png', upload_to='terefdas/'),
        ),
        migrations.AlterField(
            model_name='xəbərlər',
            name='shekil',
            field=models.ImageField(default='foto/news.jpg', upload_to='foto/'),
        ),
    ]
