# Generated by Django 2.0.7 on 2018-07-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0011_tədbir'),
    ]

    operations = [
        migrations.CreateModel(
            name='bgPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200)),
                ('shekil', models.ImageField(default='bg/cb.jpg', upload_to='layihe/')),
            ],
        ),
    ]
