# Generated by Django 2.0.7 on 2018-07-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0013_auto_20180727_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Əlaqə',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200)),
                ('shekil', models.ImageField(default='bg/cb.jpg', upload_to='Əlaqə/')),
            ],
        ),
        migrations.DeleteModel(
            name='bgPhoto',
        ),
        migrations.RemoveField(
            model_name='haqqimizda',
            name='şəkil',
        ),
        migrations.AddField(
            model_name='haqqimizda',
            name='shekil',
            field=models.ImageField(blank=True, upload_to='HaqqimizdaŞekil/'),
        ),
        migrations.AlterField(
            model_name='layihə',
            name='shekil',
            field=models.ImageField(default='layihe/proj.png', upload_to='Layihə/'),
        ),
        migrations.AlterField(
            model_name='tədbir',
            name='shekil',
            field=models.ImageField(default='layihe/proj.png', upload_to='Tədbir/'),
        ),
        migrations.AlterField(
            model_name='tərəfdaş',
            name='shekil',
            field=models.ImageField(default='terefdas/user.png', upload_to='Tərəfdaş/'),
        ),
        migrations.AlterField(
            model_name='xəbərlər',
            name='shekil',
            field=models.ImageField(default='foto/news.jpg', upload_to='Xəbərlər/'),
        ),
    ]
