# Generated by Django 2.0.7 on 2018-08-01 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0014_auto_20180727_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='haqqimizda',
            options={'verbose_name_plural': 'Haqqımızda'},
        ),
    ]
