# Generated by Django 2.0.7 on 2018-08-01 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0015_auto_20180801_1114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='əlaqə',
            options={'verbose_name_plural': 'Əlaqələr'},
        ),
    ]
