# Generated by Django 2.0.7 on 2018-08-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0016_auto_20180801_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='əlaqə',
            name='shekil',
            field=models.FileField(default='bg/cb.jpg', upload_to='Əlaqə/'),
        ),
    ]
