# Generated by Django 2.0.7 on 2018-08-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0017_auto_20180806_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='xəbərlər',
            name='tedbir',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='xəbərlər',
            name='tedbir_Link',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
