# Generated by Django 2.0.7 on 2018-08-09 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0019_auto_20180808_1424'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Əlaqə',
            new_name='Qutu',
        ),
    ]
